
export const bar = [
    {
        key:'导航',
        toPath:'/admin/navbar',
        icon:'icon-shouye1',
        slid:false
    },
    {
        key:'首页',
        icon:'icon-shouye1',
        slid:false,
        child:[
            {
                key:'头图1',
                toPath:'/admin/homeBanner1'
            },
            {
                key:'头图2',
                toPath:'/admin/homeBanner2'
            },
            {
                key:'头图3',
                toPath:'/admin/homeBanner3'
            },
            {
                key:'头图4',
                toPath:'/admin/homeBanner4'
            }
        ]
    },
    {
        key:'圈子',
        icon:'icon-shouye1',
        slid:false,
        child:[
            {
                key:'头图1',
                toPath:'/admin/homeBanner1'
            },
            {
                key:'头图2',
                toPath:'/admin/homeBanner2'
            },
            {
                key:'头图3',
                toPath:'/admin/homeBanner3'
            },
            {
                key:'头图4',
                toPath:'/admin/homeBanner4'
            }
        ]
    },
    {
        key:'管理',
        icon:'icon-shouye1',
        slid:false,
        child:[
            {
                key:'头图1',
                toPath:'/admin/homeBanner1'
            },
            {
                key:'头图2',
                toPath:'/admin/homeBanner2'
            },
            {
                key:'头图3',
                toPath:'/admin/homeBanner3'
            },
            {
                key:'头图4',
                toPath:'/admin/homeBanner4'
            }
        ]
    }
]



